# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create(name: [{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: name: 'Luke', movie: movies.first)
#AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
# City.create(name: "10th of Ramadan")
# City.create(name: "15th of May")
# City.create(name: "6th of October")
# City.create(name: "Abnub")
# City.create(name: "Abu Hammad")
# City.create(name: "Abu Hummus")
# City.create(name: "Abu Kebir")
# City.create(name: "Abu Qirqas")
# City.create(name: "Abu Suweir")
# City.create(name: "Abu Tig")
# City.create(name: "Abu El Matamir")
# City.create(name: "Aga")
# City.create(name: "Akhmim")
# City.create(name: "Alexandria")
# City.create(name: "Armant")
# City.create(name: "Ashmoun")
# City.create(name: "Aswan")
# City.create(name: "Asyut")
# City.create(name: "Badr")
# City.create(name: "Baltim")
# City.create(name: "Banha")
# City.create(name: "Basyoun")
# City.create(name: "Biyala")
# City.create(name: "Belqas")
# City.create(name: "Beni Mazar")
# City.create(name: "Beni Suef")
# City.create(name: "Beni Ebeid")
# City.create(name: "Biba")
# City.create(name: "Bilbeis")
# City.create(name: "Birket El Sab")
# City.create(name: "Borg El Burullus")
# City.create(name: "Bush")
# City.create(name: "Cairo")
# City.create(name: "Dairut")
# City.create(name: "Damanhur")
# City.create(name: "Damietta")
# City.create(name: "Dar El Salam")
# City.create(name: "Daraw")
# City.create(name: "Deir Mawas")
# City.create(name: "Dekernes")
# City.create(name: "Desouk")
# City.create(name: "Dishna")
# City.create(name: "Edfu")
# City.create(name: "Edku")
# City.create(name: "El Arish")
# City.create(name: "El Mahalla El Kubra")
# City.create(name: "El Badari")
# City.create(name: "El Bagour")
# City.create(name: "El Balyana")
# City.create(name: "El Basaliya")
# City.create(name: "El Bayadiya")
# City.create(name: "El Dabaa")
# City.create(name: "El Delengat")
# City.create(name: "El Fashn")
# City.create(name: "El Gamaliya")
# City.create(name: "El Ghanayem")
# City.create(name: "El Hamool")
# City.create(name: "El Hamam")
# City.create(name: "El Husseiniya")
# City.create(name: "El Idwa")
# City.create(name: "El Ibrahimiya")
# City.create(name: "El Tor")
# City.create(name: "El Kanayat")
# City.create(name: "El Kareen")
# City.create(name: "El Mahmoudiyah")
# City.create(name: "El-Mansha")
# City.create(name: "El Manzala")
# City.create(name: "El Maragha")
# City.create(name: "El Matareya")
# City.create(name: "El Rahmaniya")
# City.create(name: "El Reyad")
# City.create(name: "El Rhoda")
# City.create(name: "El Santa")
# City.create(name: "El Sarw")
# City.create(name: "El Sebaiya")
# City.create(name: "El Senbellawein")
# City.create(name: "El Shohada")
# City.create(name: "El Shorouk")
# City.create(name: "El Waqf")
# City.create(name: "El Wasta")
# City.create(name: "El Qantara")
# City.create(name: "El Qanater El Khayreya")
# City.create(name: "El Qoseir")
# City.create(name: "El Qusiya")
# City.create(name: "El Zarqa")
# City.create(name: "Esna")
# City.create(name: "Ezbet El Borg")
# City.create(name: "Faqous")
# City.create(name: "Faraskur")
# City.create(name: "Farshut")
# City.create(name: "Fayed")
# City.create(name: "Faiyum")
# City.create(name: "Fuka")
# City.create(name: "Girga")
# City.create(name: "Giza")
# City.create(name: "Hihya")
# City.create(name: "Hosh Essa")
# City.create(name: "Hurghada")
# City.create(name: "Ibsheway")
# City.create(name: "Ihnasiya")
# City.create(name: "Ismailia")
# City.create(name: "Itay El Barud")
# City.create(name: "Itsa")
# City.create(name: "Juhayna")
# City.create(name: "Kafr El Sheikh")
# City.create(name: "Kafr El Zayat")
# City.create(name: "Kafr El Batikh")
# City.create(name: "Kafr El Dawwar")
# City.create(name: "Kafr Saad")
# City.create(name: "Kafr Saqr")
# City.create(name: "Kafr Shukr")
# City.create(name: "Khanka")
# City.create(name: "Kharga")
# City.create(name: "Khusus")
# City.create(name: "Kom Hamada")
# City.create(name: "Kom Ombo")
# City.create(name: "Kotoor")
# City.create(name: "Luxor")
# City.create(name: "Maghagha")
# City.create(name: "Mallawi")
# City.create(name: "Manfalut")
# City.create(name: "Mansoura")
# City.create(name: "Mashtool El Souk")
# City.create(name: "Matai")
# City.create(name: "Menouf")
# City.create(name: "Marsa Alam")
# City.create(name: "Mersa Matruh")
# City.create(name: "Metoubes")
# City.create(name: "Minya")
# City.create(name: "Minyet El Nasr")
# City.create(name: "Mit Abu El Kom")
# City.create(name: "Mit Abu Ghaleb")
# City.create(name: "Mit Adlan")
# City.create(name: "Mit Bera")
# City.create(name: "Mit El Korama")
# City.create(name: "Mit Elwan")
# City.create(name: "Mit Fadala")
# City.create(name: "Mit Ghamr")
# City.create(name: "Mit Kenana")
# City.create(name: "Mit Rahina")
# City.create(name: "Mit Salsil")
# City.create(name: "Mit Sudan")
# City.create(name: "Mit Yazid")
# City.create(name: "Mut")
# City.create(name: "Nabaroh")
# City.create(name: "Nag Hammadi")
# City.create(name: "Naqada")
# City.create(name: "New Aswan")
# City.create(name: "New Akhmim")
# City.create(name: "New Asyut")
# City.create(name: "New Beni Suef")
# City.create(name: "New Borg El Arab")
# City.create(name: "New Cairo")
# City.create(name: "New Damietta")
# City.create(name: "New Faiyum")
# City.create(name: "New Minya")
# City.create(name: "New Nubariya")
# City.create(name: "New Salhia")
# City.create(name: "New Sohag")
# City.create(name: "New Tiba")
# City.create(name: "New Qena")
# City.create(name: "Obour")
# City.create(name: "Port Said")
# City.create(name: "Qaha")
# City.create(name: "Qallin")
# City.create(name: "Qalyub")
# City.create(name: "Qena")
# City.create(name: "Qift")
# City.create(name: "Quesna")
# City.create(name: "Qus")
# City.create(name: "Rafah")
# City.create(name: "Ras Burqa")
# City.create(name: "Ras El Bar")
# City.create(name: "Ras Gharib")
# City.create(name: "Ras Sedr")
# City.create(name: "Ras Shokeir")
# City.create(name: "Rosetta")
# City.create(name: "Sadat")
# City.create(name: "Safaga")
# City.create(name: "Sahel Selim")
# City.create(name: "Saint Catherine")
# City.create(name: "Samalut")
# City.create(name: "Samanoud")
# City.create(name: "Saqultah")
# City.create(name: "Senuris")
# City.create(name: "Sers El Lyan")
# City.create(name: "Sharm El Sheikh")
# City.create(name: "Sherbin")
# City.create(name: "Sheikh Zuweid")
# City.create(name: "Shibin El Qanater")
# City.create(name: "Shibin El Kom")
# City.create(name: "Shubra El Kheima")
# City.create(name: "Shubrakhit")
# City.create(name: "Sidi Barrani")
# City.create(name: "Sidi Salem")
# City.create(name: "Siwa Oasis")
# City.create(name: "Sodfa")
# City.create(name: "Sohag")
# City.create(name: "Suez")
# City.create(name: "Sumusta El Waqf")
# City.create(name: "Tahta")
# City.create(name: "Tala")
# City.create(name: "Talkha")
# City.create(name: "Tamiya")
# City.create(name: "Tanta")
# City.create(name: "Tell El Kebir")
# City.create(name: "Tima")
# City.create(name: "Tukh")
# City.create(name: "Wadi El Natrun")
# City.create(name: "Zagazig")
# City.create(name: "Zefta")

# Add book categories

bookCategories = [
    {name:"Science fiction"},
    {name:"Drama"},
    {name:"Action"},
    {name:"Adventure"},
    {name:"Romance"},
    {name:"Mystery"},
    {name:"Horror"},
    {name:"Self help"},
    {name:"Health"},
    {name:"Guide"},
    {name:"Travel"},
    {name:"Children's"},
    {name:"Religion"},
    {name:"Science"},
    {name:"History"},
    {name:"Math"},
    {name:"Fantasy"},
    {name:"Poetry"},
    {name:"Encyclopedias"},
    {name:"Dictionaries"},
    {name:"Comics"},
    {name:"Cookbooks"},
    {name:"Diaries"},
    {name:"Journals"},
    {name:"Prayer books"},
    {name:"Series"},
    {name:"Biographies"},
]
# Category.create(name: "Action")
# Category.create(name: "Adventure")
# Category.create(name: "Romance")
# Category.create(name: "Cooking")
# Category.create(name: "History")
# Category.create(name: "Poetry")
# Category.create(name: "Encyclopedia")
Category.create(bookCategories)